name: Build and Deploy Java Azure Function

on:
  push:
    branches:
      - main  # your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven and package Azure Function
        run: mvn clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: azure-function-artifact
          path: target/*.jar  # adjust if your artifact is somewhere else

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: azure-function-artifact
          path: ./artifact

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: javafunction
          package: './artifact/*.jar'  # matches the downloaded artifact
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
