name: Build and Deploy Java Azure Function

on:
  push:
    branches:
      - main  # Run only on main branch commits

env:
  AZURE_FUNCTIONAPP_NAME: 'javafunction'           # Replace with your actual function app name
  POM_XML_DIRECTORY: '.'                           # pom.xml is at the root
  JAVA_VERSION: '17'                               # Java version used
  ZIP_NAME: 'functionapp.zip'                      # Output ZIP file

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        shell: pwsh
        run: |
          pushd '${{ env.POM_XML_DIRECTORY }}'
          mvn clean package azure-functions:package
          popd

      - name: Create ZIP for deployment
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ env.POM_XML_DIRECTORY }}/target/azure-functions/javafunction/*" `
                           -DestinationPath "${{ env.POM_XML_DIRECTORY }}/target/${{ env.ZIP_NAME }}"

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.POM_XML_DIRECTORY }}/target/${{ env.ZIP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
