name: Build and Deploy Java Azure Function (No App Settings)

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'javafunction'          # Replace with your Function App name
  POM_XML_DIRECTORY: '.'                          # Where your pom.xml lives
  JAVA_VERSION: '17'
  ZIP_NAME: 'functionapp.zip'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build the project with Maven
        shell: pwsh
        run: |
          pushd '${{ env.POM_XML_DIRECTORY }}'
          mvn clean package azure-functions:package
          popd

      - name: Zip function app output
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ env.POM_XML_DIRECTORY }}/target/azure-functions/javafunction/*" `
                           -DestinationPath "${{ env.POM_XML_DIRECTORY }}/target/${{ env.ZIP_NAME }}"

      - name: Deploy via cURL to Kudu ZIP Deploy API
        shell: pwsh
        run: |
          $publishXml = '${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
          $username = ($publishXml -split 'userName="')[1] -split '"' | Select-Object -First 1
          $password = ($publishXml -split 'userPWD="')[1] -split '"' | Select-Object -First 1
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$username`:$password"))

          $headers = @{ Authorization = "Basic $base64AuthInfo" }

          Invoke-RestMethod `
            -Uri "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy" `
            -Method POST `
            -Headers $headers `
            -InFile "${{ env.POM_XML_DIRECTORY }}/target/${{ env.ZIP_NAME }}" `
            -ContentType "application/zip"
