name: Build and Deploy Java Azure Function

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or use your version
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean package

      - name: List contents of target folder (for debugging)
        run: ls -R target/

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'javafunction'  # 🔁 Replace with your Azure Function App name
          package: 'target/azure-functions/<your-function-name>-1.0-SNAPSHOT.zip'  # 🔁 Check your exact .zip name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
