name: Build and Deploy Java Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: List files for debugging
        run: ls -lR target

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: javafunction
          package: '${{ github.workspace }}/target/azure-function-hello-1.0-SNAPSHOT.jar'  # Adjust this path based on ls output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
