name: Deploy Java project to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'javafunction'
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java SDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build project with Maven
        shell: pwsh
        run: |
          pushd '${{ env.POM_XML_DIRECTORY }}'
          mvn clean package azure-functions:package
          popd

      - name: Zip function app contents
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ env.POM_XML_DIRECTORY }}/target/azure-functions/javafunction/*" `
                           -DestinationPath "${{ env.POM_XML_DIRECTORY }}/target/javafunction.zip"

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.POM_XML_DIRECTORY }}/target/javafunction.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
